### ISSUE TITLE
certifi package not found on Docker

### ISSUE THREAD

**Issue by jhugon** [jhugon/semantic-data-taking-webapp#40]
For some reason Docker leads to a `ModuleNotFoundError: No module named 'certifi'` error both locally and in the cloud. It's confusing since the package is pinned in the Pipfile.loc

**Comment by SamirPS** [comment]
Yeah but didn't see the certifi package in the Pipfile

**Comment by jhugon** [comment]
The problem seems to have gone away. I think a package installed by `pip install pipenv` could have been the problem.

Went ahead an put gunicorn in the Pipfile to try to lock things down better in the Pipfile.lock, even though I don't think it would have helped this time.
